# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_id',
            field=models.CharField(db_index=True, default=1, max_length=40),
            preserve_default=False,
        ),
    ]
