# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='session_id',
            field=models.CharField(max_length=40),
        ),
    ]
