# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170421_2229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='MCart',
        ),
    ]
