# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170423_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cod',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='cod',
            field=models.PositiveIntegerField(),
        ),
    ]
